[package]
name = "assemble-std"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assemble-core = { path = "../assemble-core", features = ["derive"]}
thiserror = "1.0.31"
