[package]
name = "assemble-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
internal = []
derive = ["internal", "assemble-macros"]

[dependencies]
petgraph = "0.6.0"
static_assertions = "1.1.0"
thiserror = "1.0.30"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
serde = { version = "1.0.137", features = ["derive"] }
once_cell = "1.12.0"
url = "2.2.2"
include_dir = "0.7.2"
tempdir = "0.3.7"
clap = "3.1.18"
log = "0.4.17"
assemble-macros = { path = "../assemble-macros", optional =true }
fern = "0.6.1"
colored = "2.0.0"
time = "0.3.9"
