[package]
name = "assemble-rs"
version = "0.1.0"
authors = ["Joshua Radin <jradin16@gmail.com"]
edition = "2021"

[dependencies]
clap = { version = "3.1.18", features = ["derive"] }
assemble-core = {path = "../assemble-core", version = "*"}