[package]
name = "assemble"
version = "0.1.1"
authors = ["Joshua Radin <jradin16@gmail.com"]
edition = "2021"

[features]
default = []
yaml = ["serde_yaml"]

[dependencies]
assemble-core = { path = "../assemble-core", version = "*", features = ["derive", "text_factory"] }
assemble-freight = { version = "0.1.1", path = "../assemble-freight" }
serde = { version = "1.0.143", features = ["derive"] }
serde_yaml = { version = "0.9.9", optional = true }
thiserror = "1.0.32"
log = "0.4.17"
heck = "0.4.0"
itertools = "0.10.3"

