[package]
name = "assemble-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro=true

[dependencies]
syn = { version = "1.0.94", features = ["full", "visit", "extra-traits"] }
quote = "1.0.18"
proc-macro2 = "1.0.39"
