name: Create Release

on:
  workflow_dispatch:
    inputs:
      patchType:
        description: "Patch type"
        required: false
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  validate-release:
    name: "Validates whether the next version is valid"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rust-docs

      - name: Install needed tools
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: cargo-edit cargo-semver-checks@0.8.0

      - name: Update version
        uses: actions-rs/cargo@v1
        with:
          command: set-version
          args: --bump ${{ inputs.patchType }}

      - name: Update dependencies
        uses: actions-rs/cargo@v1
        with:
          command: update

      - name: Commit version update
        uses: EndBug/add-and-commit@v9
        with:
          default_author: user_info
          message: Updating version of assemble
          push: false

      - name: Semver checks
        uses: actions-rs/cargo@v1
        with:
          command: semver-checks
          args: check-release -p assemble-core -vvv
          toolchain: nightly

      - name: Push commit
        run: |
          git config --global user.name 'Joshua Radin'
          git config --global user.email 'joshradin@users.noreply.github.com'
          git push

