name: Publish Assets

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  get-version:
    name: Get version
    runs-on: ubuntu-latest
    steps:
     - name: Get version string
       run: echo "ASSEMBLE_VERSION=$(echo ${{ github.ref }} | cut -d/ -f3)" >> $GITHUB_ENV

  publish-binaries:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: asmbl
            asset_name: assemble-linux-amd64
          - os: windows-latest
            artifact_name: asmbl.exe
            asset_name: assemble-windows-amd64.exe
          - os: macos-latest
            artifact_name: asmbl
            asset_name: assemble-macos-amd64

    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --all-features --release --bin assemble
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}-${{ env.ASSEMBLE_VERSION }}
          tag: ${{ github.ref }}

  publish-ts:
    name: Publish typescript sources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: compress ts files
        uses: a7u1/tar-action@v1.10
        id: compressed
        with:
            cwd: ./crates/assemble-js/src/ts
            files: |
              *.ts
            outPath: assemble-ts-${{ env.ASSEMBLE_VERSION }}.tar.gz
      - name: publish created tar file
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: assemble-ts-${{ env.ASSEMBLE_VERSION }}.tar.gz
          asset_name: assemble-ts-${{ env.ASSEMBLE_VERSION }}.tar.gz
          tag: ${{ github.ref }}

