name: Publish Assets

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-binaries:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: assemble
            asset_name: assemble-linux-amd64
          - os: windows-latest
            artifact_name: assemble.exe
            asset_name: assemble-windows-amd64.exe
          - os: macos-latest
            artifact_name: assemble
            asset_name: assemble-macos-amd64

    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --all-features --release --bin assemble
      - name: Get version string
        run: echo "ASSEMBLE_VERSION=$(echo ${{ github.ref }} | cut -d/ -f3)" >> $GITHUB_ENV
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}-${{ env.ASSEMBLE_VERSION }}
          tag: ${{ github.ref }}
