name: Publish

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish-binaries:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: assemble
            asset_name: assemble-linux-amd64
          - os: windows-latest
            artifact_name: assemble.exe
            asset_name: assemble-windows-amd64.exe
          - os: macos-latest
            artifact_name: assemble
            asset_name: assemble-macos-amd64

    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs:
      - publish-libraries

    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build
        run: cargo build --all-features --release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}


  publish-libraries:
    name: Publish to crates-io
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Get tag name
        if: ${{ failure() }}
        run: echo TAG_NAME=$(echo ${{ github.ref }} |cut -d / -f 3) >> $GITHUB_ENV
      - name: Delete tag on failure
        if: ${{ failure() }}
        uses: dev-drprasad/delete-tag-and-release@v0.2.0
        with:
          delete_release: true
          tag_name: ${{ env.TAG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


